creativecreatorormaybenot/github-tracker

backend/functions/src/content-repos.ts

Improve the content repos list.
Closes #18.

Add more content repos

---

backend/functions/src/index.ts

Add fastest growing of the past week

---

.github/workflows/hosting.yml
.github/workflows/preview.yml
frontend/github_tracker/lib/main.dart
frontend/github_tracker/web/favicon.png
frontend/github_tracker/web/icons/Icon-192.png
frontend/github_tracker/web/icons/Icon-512.png
frontend/github_tracker/web/icons/icon_120.png
frontend/github_tracker/web/icons/icon_128.png
frontend/github_tracker/web/icons/icon_144.png
frontend/github_tracker/web/icons/icon_152.png
frontend/github_tracker/web/icons/icon_180.png
frontend/github_tracker/web/icons/icon_192.png
frontend/github_tracker/web/icons/icon_196.png
frontend/github_tracker/web/icons/icon_256.png
frontend/github_tracker/web/icons/icon_32.png
frontend/github_tracker/web/icons/icon_512.png
frontend/github_tracker/web/icons/icon_57.png
frontend/github_tracker/web/icons/icon_72.png
frontend/github_tracker/web/icons/icon_76.png
frontend/github_tracker/web/icons/icon_96.png
frontend/github_tracker/web/index.html
frontend/github_tracker/web/manifest.json
frontend/github_tracker/web/og/github_tracker_logo.png

Finalize icon

---

frontend/github_tracker/lib/main.dart
frontend/github_tracker/pubspec.lock
frontend/github_tracker/pubspec.yaml

Use path URL strategy

---

frontend/github_tracker/analysis_options.yaml
frontend/github_tracker/pubspec.lock
frontend/github_tracker/pubspec.yaml
frontend/github_tracker/test/widget_test.dart

Switch to flutter_lints

---

frontend/github_tracker/lib/data/auth.dart
frontend/github_tracker/lib/data/html/_loader_html.dart
frontend/github_tracker/lib/data/html/_loader_stub.dart
frontend/github_tracker/lib/data/html/loader.dart
frontend/github_tracker/lib/data/strings.dart
frontend/github_tracker/lib/main.dart
frontend/github_tracker/lib/providers/auth.dart
frontend/github_tracker/lib/widgets/auth_barrier.dart
frontend/github_tracker/lib/widgets/error_code.dart
frontend/github_tracker/pubspec.lock
frontend/github_tracker/pubspec.yaml
frontend/github_tracker/web/index.html

Improves the user experience by:
* Removing the loader on load.
* Adding error codes.
* Not requiring to reload to use the app first time :)

Improve UX

---

frontend/github_tracker/lib/widgets/auth_barrier.dart
frontend/github_tracker/lib/widgets/dashboard.dart
frontend/github_tracker/pubspec.lock
frontend/github_tracker/pubspec.yaml

See https://github.com/rrousselGit/river_pod/issues/531 for upcoming changes that might require additional refactoring.
Note to anyone viewing this from the outside: the Flutter app is still in the debugging phase, which means that the code is not representative of what it will look like for the MVP.

Migrate to riverpod 1.0.0

---

backend/functions/package-lock.json
backend/functions/package.json
backend/functions/src/blurhash.ts

Use Jimp for blurhash

---

backend/functions/src/data.ts

Fixes the blur hash not being written.

Use deep merge for avatar

---

frontend/github_tracker/lib/data/firestore/repo_stats.dart
frontend/github_tracker/lib/data/strings.dart
frontend/github_tracker/lib/main.dart
frontend/github_tracker/lib/models/dashboard_state.dart
frontend/github_tracker/lib/models/repo_stats.dart
frontend/github_tracker/lib/providers/dashboard.dart
frontend/github_tracker/lib/widgets/app.dart
frontend/github_tracker/lib/widgets/dashboard.dart
frontend/github_tracker/lib/widgets/error_code.dart
frontend/github_tracker/lib/widgets/link.dart
frontend/github_tracker/lib/widgets/stats_change.dart
frontend/github_tracker/lib/widgets/stats_table.dart
frontend/github_tracker/pubspec.yaml
frontend/github_tracker/test/models/repo_stats_test.dart
frontend/github_tracker/web/index.html

As well as a few other UI/UX improvements :)

 Show change values in frontened 

---

frontend/github_tracker/lib/data/auth.dart
frontend/github_tracker/lib/providers/auth.dart
frontend/github_tracker/lib/widgets/auth_barrier.dart
frontend/github_tracker/lib/widgets/error_code.dart
frontend/github_tracker/pubspec.lock
frontend/github_tracker/pubspec.yaml

Fix session barrier

---

backend/functions/package-lock.json
backend/functions/package.json
backend/functions/src/data.ts
frontend/github_tracker/lib/models/repo_stats.dart

* Fixes deploy
* Resolves #174

Update Node and types

---

backend/functions/src/data.ts

Fix top 100 integrity & reenable position tracking

---

backend/functions/src/data.ts

Fix invalid Twitter hashtags

---

frontend/github_tracker/web/index.html

Update open graph tags

---

backend/functions/src/data.ts

I hope this works. I never used TypeScript before.
Fixes #213

Hashtags are now checking for "#" and replace it with "sharp"

---

backend/functions/package-lock.json
backend/functions/src/data.ts
backend/functions/src/index.ts
backend/functions/src/tweets.ts

Only post one tweet at a time

---

backend/functions/src/backups.ts
backend/functions/src/extract.ts

We want to backup daily once we have less docs in the database.

Change backup strategy

---

backend/functions/src/extract.ts

Delete documents in extraction

---

backend/functions/src/extract.ts

Fixes the logging to actually display the dates.

Fix date logs

---

.github/workflows/hosting.yml
.github/workflows/preview.yml
frontend/github_tracker/pubspec.lock

Switching deployment to stable fixes the rendering bugs of images.
Closes #365

Switch to stable

---

.vscode/launch.json
frontend/github_tracker/lib/widgets/dashboard.dart
frontend/github_tracker/lib/widgets/stats_table.dart

Animate paging in stats table

---

frontend/github_tracker/lib/widgets/link.dart

Fix link color in dark mode

---

backend/cloud_functions/src/application/track/content-repos.ts

These repos are strictly content-only.

Untrack several content repos
